import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisScroller from "./Components/UI/LenisScroller";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Parth Ganjoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisScroller /> 
        {children}
      </body>
    </html>
  );
}
